### PR TITLE
Adds Code of conduct copy from other ddi projects

### PR DESCRIPTION
**Pull request by Caralin**
Just a copy of the file from the other ddi projects - saw we didn't have one yet when I went looking for contribution guides :)

### CODE REVIEW

**Comment by zenlan** [comment]
Would this be better merged into the front page, the main README.md file?

**Comment by Caralin** [comment]
you can set the Code of Conduct as a file in Insights > Community

**Comment by Caralin** [comment]
it's set automatically?

but we probably should have a link to the Project Code of Conduct in a revised version of the main README

**Comment by zenlan** [comment]
Ah, I see! I was not aware of that.

**Pull request merged**
